name: Discord Webhook
on:
  workflow_dispatch:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          VERSION="${{ env.VERSION }}"
          jq -n --arg content "## RP Dice ${VERSION}

          ${CHANGELOG}

          **You can download this version [here](https://modrinth.com/plugin/rp-dice/version/${VERSION})!**
          <@&1524551634326126632>" \
          '{"content": $content, "flags": 4}' | \
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d @-
