name: Publish Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          body_path: CHANGELOG.md
          files: build/libs/rpDice-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/rpDice-${{ env.VERSION }}.jar
  modrinth:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Load changelog
        id: changelog
        run: |
          echo "content=$(jq -Rs . CHANGELOG.md)" >> $GITHUB_OUTPUT

      - name: Download plugin jar artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: bmeFJq7B
          modrinth-token: ${{ secrets.MODRINTH_SECRET }}

          files: build/libs/rpDice-${{ env.VERSION }}.jar
          version: ${{ env.VERSION }}
          version-type: release

          loaders: |
            paper
            purpur

          game-versions: |
            1.21.x
            26.1.x
            26.2

          changelog: |
            # RP Dice ${{ env.VERSION }}
            
            ${{ fromJSON(steps.changelog.outputs.content) }}
            
            **To update the plugin, just delete the old version and drag the new one into the plugins folder. I recommend to first boot up test server and see config changes**
            
            If you find any issues or want to suggest features, please open an issue on my github repo [--> here <--](https://github.com/lordofthetimes/RP-Dice/issues)
  
  

  discord:
    runs-on: ubuntu-latest
    needs: modrinth
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          VERSION="${{ env.VERSION }}"
          jq -n --arg content "## RP Dice ${VERSION}

          ${CHANGELOG}

          **You can download this version [here](https://modrinth.com/plugin/rp-dice/version/${VERSION})!**
          <@&1524551634326126632>" \
          '{"content": $content, "flags": 4}' | \
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d @-
